import type { Metadata } from "next";
import { Geist_Mono, Sofia_Sans_Extra_Condensed} from "next/font/google";
import "./globals.css";

// Load Sofia Sans Condensed as main font
const sofia = Sofia_Sans_Extra_Condensed({
    variable: "--font-sofia", // 👈 Use a semantic name
    subsets: ["latin"],
});

// Optional: Keep Geist Mono as monospace font
const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${sofia.variable} ${geistMono.variable} antialiased font-sans`}
        >
        {children}
        </body>
        </html>
    );
}
